# Form implementation generated from reading ui file '.\ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 265)
        MainWindow.setMinimumSize(QtCore.QSize(480, 220))
        MainWindow.setMaximumSize(QtCore.QSize(480, 265))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ico.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: #74673e;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.start_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start_button.setMinimumSize(QtCore.QSize(0, 28))
        self.start_button.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 6px;\n"
"border-color: #534928;\n"
"background-color:#423e23;\n"
"color:#d1b17f;\n"
"font-weight: 600;\n"
"}\n"
"QPushButton:pressed{\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"background-color:#423e23;\n"
"color:#d1b17f;\n"
"font-weight: 600;\n"
"}")
        self.start_button.setObjectName("start_button")
        self.gridLayout.addWidget(self.start_button, 1, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 6px;\n"
"border-color: #534928;\n"
"background-color:#423e23;\n"
"color:#d1b17f;\n"
"font-weight: 600;\n"
"}\n"
"QPushButton:pressed{\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"background-color:#423e23;\n"
"color:#d1b17f;\n"
"font-weight: 600;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 2)
        self.file_pick_button = QtWidgets.QToolButton(parent=self.centralwidget)
        self.file_pick_button.setMinimumSize(QtCore.QSize(28, 28))
        self.file_pick_button.setMaximumSize(QtCore.QSize(28, 28))
        self.file_pick_button.setStyleSheet("QToolButton{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 6px;\n"
"border-color: #534928;\n"
"background-color:#423e23;\n"
"color:#d1b17f;\n"
"}\n"
"QToolButton:pressed{\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"background-color:#423e23;\n"
"color:#d1b17f;\n"
"}")
        self.file_pick_button.setObjectName("file_pick_button")
        self.gridLayout.addWidget(self.file_pick_button, 0, 1, 1, 1)
        self.junk = QtWidgets.QLabel(parent=self.centralwidget)
        self.junk.setObjectName("junk")
        self.gridLayout.addWidget(self.junk, 3, 0, 1, 1)
        self.backup_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.backup_button.setMinimumSize(QtCore.QSize(0, 28))
        self.backup_button.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 6px;\n"
"border-color: #534928;\n"
"background-color:#423e23;\n"
"color:#d1b17f;\n"
"font-weight: 600;\n"
"}\n"
"QPushButton:pressed{\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"background-color:#423e23;\n"
"color:#d1b17f;\n"
"font-weight: 600;\n"
"}")
        self.backup_button.setObjectName("backup_button")
        self.gridLayout.addWidget(self.backup_button, 6, 0, 1, 2)
        self.save_picker_combo_box = QtWidgets.QComboBox(parent=self.centralwidget)
        self.save_picker_combo_box.setMinimumSize(QtCore.QSize(0, 28))
        self.save_picker_combo_box.setStyleSheet("color: #423923;\n"
"background-color: #d0b47d;\n"
"font-weight: 600;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 6px;\n"
"border-color: #74673e;")
        self.save_picker_combo_box.setObjectName("save_picker_combo_box")
        self.gridLayout.addWidget(self.save_picker_combo_box, 4, 0, 1, 2)
        self.path_to_save_line_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.path_to_save_line_edit.setMinimumSize(QtCore.QSize(0, 28))
        self.path_to_save_line_edit.setStyleSheet("color: #423923;\n"
"background-color: #d0b47d;\n"
"font-weight: 600;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 6px;\n"
"border-color: #74673e;")
        self.path_to_save_line_edit.setObjectName("path_to_save_line_edit")
        self.gridLayout.addWidget(self.path_to_save_line_edit, 0, 0, 1, 1)
        self.clear_Backups = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clear_Backups.setMinimumSize(QtCore.QSize(0, 28))
        self.clear_Backups.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 6px;\n"
"border-color: #534928;\n"
"background-color:#423e23;\n"
"color:#d1b17f;\n"
"font-weight: 600;\n"
"}\n"
"QPushButton:pressed{\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"background-color:#423e23;\n"
"color:#d1b17f;\n"
"font-weight: 600;\n"
"}")
        self.clear_Backups.setObjectName("clear_Backups")
        self.gridLayout.addWidget(self.clear_Backups, 7, 0, 2, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setStyleSheet("background-color: #74673e;\n"
"color:#d1b17f;\n"
"font-weight: 600;")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Iron man keeper by ChezZz"))
        self.start_button.setText(_translate("MainWindow", "Автоматическое сохранение"))
        self.pushButton.setText(_translate("MainWindow", "Сохранить"))
        self.file_pick_button.setText(_translate("MainWindow", "..."))
        self.backup_button.setText(_translate("MainWindow", "Восстановить"))
        self.path_to_save_line_edit.setPlaceholderText(_translate("MainWindow", "Путь до сохранения"))
        self.clear_Backups.setText(_translate("MainWindow", "Очистить бэкапы для этого сохранения"))